apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-operator
  template:
    metadata:
      labels:
        name: zookeeper-operator
    spec:
      containers:
      - name: zookeeper-operator
        image: zookeeper-operator:0.1.0
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:  ["zookeeper-operator"]
        args: ["--namespace=$(MY_POD_NAMESPACE)", "--leader-elect=true"]
