/*
Copyright 2018 The zookeeper-operator Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"
	zookeeperv1alpha1 "zookeeper-operator/pkg/apis/zookeeper/v1alpha1"
	versioned "zookeeper-operator/pkg/client/clientset/versioned"
	internalinterfaces "zookeeper-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "zookeeper-operator/pkg/client/listers/zookeeper/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ZookeeperClusterInformer provides access to a shared informer and lister for
// ZookeeperClusters.
type ZookeeperClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ZookeeperClusterLister
}

type zookeeperClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewZookeeperClusterInformer constructs a new informer for ZookeeperCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewZookeeperClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredZookeeperClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredZookeeperClusterInformer constructs a new informer for ZookeeperCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredZookeeperClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZookeeperV1alpha1().ZookeeperClusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZookeeperV1alpha1().ZookeeperClusters(namespace).Watch(context.TODO(), options)
			},
		},
		&zookeeperv1alpha1.ZookeeperCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *zookeeperClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredZookeeperClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *zookeeperClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&zookeeperv1alpha1.ZookeeperCluster{}, f.defaultInformer)
}

func (f *zookeeperClusterInformer) Lister() v1alpha1.ZookeeperClusterLister {
	return v1alpha1.NewZookeeperClusterLister(f.Informer().GetIndexer())
}
