/*
Copyright 2018 The zookeeper-operator Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "zookeeper-operator/pkg/apis/zookeeper/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeZookeeperClusters implements ZookeeperClusterInterface
type FakeZookeeperClusters struct {
	Fake *FakeZookeeperV1alpha1
	ns   string
}

var zookeeperclustersResource = schema.GroupVersionResource{Group: "zookeeper", Version: "v1alpha1", Resource: "zookeeperclusters"}

var zookeeperclustersKind = schema.GroupVersionKind{Group: "zookeeper", Version: "v1alpha1", Kind: "ZookeeperCluster"}

// Get takes name of the zookeeperCluster, and returns the corresponding zookeeperCluster object, and an error if there is any.
func (c *FakeZookeeperClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.ZookeeperCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(zookeeperclustersResource, c.ns, name), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}

// List takes label and field selectors, and returns the list of ZookeeperClusters that match those selectors.
func (c *FakeZookeeperClusters) List(opts v1.ListOptions) (result *v1alpha1.ZookeeperClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(zookeeperclustersResource, zookeeperclustersKind, c.ns, opts), &v1alpha1.ZookeeperClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ZookeeperClusterList{ListMeta: obj.(*v1alpha1.ZookeeperClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.ZookeeperClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested zookeeperClusters.
func (c *FakeZookeeperClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(zookeeperclustersResource, c.ns, opts))

}

// Create takes the representation of a zookeeperCluster and creates it.  Returns the server's representation of the zookeeperCluster, and an error, if there is any.
func (c *FakeZookeeperClusters) Create(zookeeperCluster *v1alpha1.ZookeeperCluster) (result *v1alpha1.ZookeeperCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(zookeeperclustersResource, c.ns, zookeeperCluster), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}

// Update takes the representation of a zookeeperCluster and updates it. Returns the server's representation of the zookeeperCluster, and an error, if there is any.
func (c *FakeZookeeperClusters) Update(zookeeperCluster *v1alpha1.ZookeeperCluster) (result *v1alpha1.ZookeeperCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(zookeeperclustersResource, c.ns, zookeeperCluster), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeZookeeperClusters) UpdateStatus(zookeeperCluster *v1alpha1.ZookeeperCluster) (*v1alpha1.ZookeeperCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(zookeeperclustersResource, "status", c.ns, zookeeperCluster), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}

// Delete takes name of the zookeeperCluster and deletes it. Returns an error if one occurs.
func (c *FakeZookeeperClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(zookeeperclustersResource, c.ns, name), &v1alpha1.ZookeeperCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeZookeeperClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(zookeeperclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ZookeeperClusterList{})
	return err
}

// Patch applies the patch and returns the patched zookeeperCluster.
func (c *FakeZookeeperClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ZookeeperCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(zookeeperclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}
