/*
Copyright 2018 The zookeeper-operator Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"
	v1alpha1 "zookeeper-operator/pkg/apis/zookeeper/v1alpha1"
	scheme "zookeeper-operator/pkg/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ZookeeperClustersGetter has a method to return a ZookeeperClusterInterface.
// A group's client should implement this interface.
type ZookeeperClustersGetter interface {
	ZookeeperClusters(namespace string) ZookeeperClusterInterface
}

// ZookeeperClusterInterface has methods to work with ZookeeperCluster resources.
type ZookeeperClusterInterface interface {
	Create(*v1alpha1.ZookeeperCluster) (*v1alpha1.ZookeeperCluster, error)
	Update(*v1alpha1.ZookeeperCluster) (*v1alpha1.ZookeeperCluster, error)
	UpdateStatus(*v1alpha1.ZookeeperCluster) (*v1alpha1.ZookeeperCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ZookeeperCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.ZookeeperClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ZookeeperCluster, err error)
	ZookeeperClusterExpansion
}

// zookeeperClusters implements ZookeeperClusterInterface
type zookeeperClusters struct {
	client rest.Interface
	ns     string
}

// newZookeeperClusters returns a ZookeeperClusters
func newZookeeperClusters(c *ZookeeperV1alpha1Client, namespace string) *zookeeperClusters {
	return &zookeeperClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the zookeeperCluster, and returns the corresponding zookeeperCluster object, and an error if there is any.
func (c *zookeeperClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.ZookeeperCluster, err error) {
	result = &v1alpha1.ZookeeperCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("zookeeperclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ZookeeperClusters that match those selectors.
func (c *zookeeperClusters) List(opts v1.ListOptions) (result *v1alpha1.ZookeeperClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ZookeeperClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("zookeeperclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested zookeeperClusters.
func (c *zookeeperClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("zookeeperclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a zookeeperCluster and creates it.  Returns the server's representation of the zookeeperCluster, and an error, if there is any.
func (c *zookeeperClusters) Create(zookeeperCluster *v1alpha1.ZookeeperCluster) (result *v1alpha1.ZookeeperCluster, err error) {
	result = &v1alpha1.ZookeeperCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("zookeeperclusters").
		Body(zookeeperCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a zookeeperCluster and updates it. Returns the server's representation of the zookeeperCluster, and an error, if there is any.
func (c *zookeeperClusters) Update(zookeeperCluster *v1alpha1.ZookeeperCluster) (result *v1alpha1.ZookeeperCluster, err error) {
	result = &v1alpha1.ZookeeperCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("zookeeperclusters").
		Name(zookeeperCluster.Name).
		Body(zookeeperCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *zookeeperClusters) UpdateStatus(zookeeperCluster *v1alpha1.ZookeeperCluster) (result *v1alpha1.ZookeeperCluster, err error) {
	result = &v1alpha1.ZookeeperCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("zookeeperclusters").
		Name(zookeeperCluster.Name).
		SubResource("status").
		Body(zookeeperCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the zookeeperCluster and deletes it. Returns an error if one occurs.
func (c *zookeeperClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("zookeeperclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *zookeeperClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("zookeeperclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched zookeeperCluster.
func (c *zookeeperClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ZookeeperCluster, err error) {
	result = &v1alpha1.ZookeeperCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("zookeeperclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
